services:
  - type: web
    name: indian-stock-market-tracker
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false 